name: skyblock
main: de.qgel.skyblock.skyblock
version: 0.2.2
description: skyblock plugin. Survive on a small island in the sky with only basic supplies. Try to beat the challenges. to see the challenges type /skyhelp challenges or /skyhelp c
softdepend: [CleanroomGenerator,Multiverse-Core]
authors: [Qgel, Payam]
commands:
    removeIsland:
        description: Removes the island of a given player.
        usage:  |
            /removeIsland <playername>
    island:
        description: Teleport to your island.
        usage:  |
            /island
    is:
        description: Teleport to your island.
        usage:  |
            /is
    skyHelp:
        description: Outputs all the commands and info about the skyblock plugin
        usage:  |
            /skyHelp [c(hallenges)]